---
abstract: 'Lazily turn multi-level hashes of configuration data in to objects with error catching and defaults'
author:
  - "['Peter Sergeant <pete@clueball.com>']"
build_requires:
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Class-ConfigHash
requires:
  Carp: 0
  Test::Exception: 0
  Test::More: 0
version: 0.001
